// src/constants/phoneCountryMap.ts

import type { CountryCode } from '@/constants/country'
import type { CallingCode } from '@/constants/callingCode'

export const countryToCallingCodeMap: Record<CountryCode, CallingCode> = {
  AR: '+54',
  AT: '+43',
  BE: '+32',
  BR: '+55',
  CA: '+1',
  CH: '+41',
  CL: '+56',
  CO: '+57',
  CU: '+53',
  DE: '+49',
  DK: '+45',
  EG: '+20',
  ES: '+34',
  FR: '+33',
  GB: '+44',
  GR: '+30',
  HU: '+36',
  IT: '+39',
  KZ: '+7',
  MX: '+52',
  MY: '+60',
  NL: '+31',
  NO: '+47',
  PE: '+51',
  PL: '+48',
  RO: '+40',
  RU: '+7',
  SJ: '+47',
  SE: '+46',
  US: '+1',
  VE: '+58',
  ZA: '+27',
}

export const callingCodeToCountriesMap: Record<CallingCode, CountryCode[]> = {
  '+1': ['US', 'CA'],
  '+7': ['KZ', 'RU'],
  '+20': ['EG'],
  '+27': ['ZA'],
  '+30': ['GR'],
  '+31': ['NL'],
  '+32': ['BE'],
  '+33': ['FR'],
  '+34': ['ES'],
  '+36': ['HU'],
  '+39': ['IT'],
  '+40': ['RO'],
  '+41': ['CH'],
  '+43': ['AT'],
  '+44': ['GB'],
  '+45': ['DK'],
  '+46': ['SE'],
  '+47': ['NO', 'SJ'],
  '+48': ['PL'],
  '+49': ['DE'],
  '+51': ['PE'],
  '+52': ['MX'],
  '+53': ['CU'],
  '+54': ['AR'],
  '+55': ['BR'],
  '+56': ['CL'],
  '+57': ['CO'],
  '+58': ['VE'],
  '+60': ['MY'],
}
